// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Batch struct {
	ID                string
	ItemID            sql.NullString
	InitialQuantity   int32
	CurrentQuantity   int32
	InTransitQuantity int32
	ExpirationDate    sql.NullTime
	CreatedAt         sql.NullTime
}

type Category struct {
	ID               string
	Name             string
	Description      sql.NullString
	IsPerishable     bool
	IsDurable        bool
	HazardLevel      int32
	IsBatchRetrieved bool
	IsIndividual     bool
	CreatedAt        sql.NullTime
}

type Item struct {
	ID             string
	Description    sql.NullString
	Name           string
	ExternalID     sql.NullString
	CategoryID     sql.NullString
	IsInStock      sql.NullBool
	ExpirationDate sql.NullTime
	CreatedAt      sql.NullTime
}
